// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/drone_handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/drone_handler.go -destination=internal/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "DroneManager/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDroneRepository is a mock of DroneRepository interface.
type MockDroneRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDroneRepositoryMockRecorder
	isgomock struct{}
}

// MockDroneRepositoryMockRecorder is the mock recorder for MockDroneRepository.
type MockDroneRepositoryMockRecorder struct {
	mock *MockDroneRepository
}

// NewMockDroneRepository creates a new mock instance.
func NewMockDroneRepository(ctrl *gomock.Controller) *MockDroneRepository {
	mock := &MockDroneRepository{ctrl: ctrl}
	mock.recorder = &MockDroneRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDroneRepository) EXPECT() *MockDroneRepositoryMockRecorder {
	return m.recorder
}

// CreateDrone mocks base method.
func (m *MockDroneRepository) CreateDrone(drone models.Drone) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDrone", drone)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDrone indicates an expected call of CreateDrone.
func (mr *MockDroneRepositoryMockRecorder) CreateDrone(drone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDrone", reflect.TypeOf((*MockDroneRepository)(nil).CreateDrone), drone)
}

// GetAllDrones mocks base method.
func (m *MockDroneRepository) GetAllDrones() ([]models.Drone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDrones")
	ret0, _ := ret[0].([]models.Drone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDrones indicates an expected call of GetAllDrones.
func (mr *MockDroneRepositoryMockRecorder) GetAllDrones() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDrones", reflect.TypeOf((*MockDroneRepository)(nil).GetAllDrones))
}

// UpdateDrone mocks base method.
func (m *MockDroneRepository) UpdateDrone(idString string, updateData models.Drone) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDrone", idString, updateData)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDrone indicates an expected call of UpdateDrone.
func (mr *MockDroneRepositoryMockRecorder) UpdateDrone(idString, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDrone", reflect.TypeOf((*MockDroneRepository)(nil).UpdateDrone), idString, updateData)
}
