// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/drone.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDroneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Charge        int32                  `protobuf:"varint,3,opt,name=charge,proto3" json:"charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDroneRequest) Reset() {
	*x = CreateDroneRequest{}
	mi := &file_proto_drone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDroneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDroneRequest) ProtoMessage() {}

func (x *CreateDroneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDroneRequest.ProtoReflect.Descriptor instead.
func (*CreateDroneRequest) Descriptor() ([]byte, []int) {
	return file_proto_drone_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDroneRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateDroneRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *CreateDroneRequest) GetCharge() int32 {
	if x != nil {
		return x.Charge
	}
	return 0
}

type UpdateDroneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Charge        int32                  `protobuf:"varint,3,opt,name=charge,proto3" json:"charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDroneRequest) Reset() {
	*x = UpdateDroneRequest{}
	mi := &file_proto_drone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDroneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDroneRequest) ProtoMessage() {}

func (x *UpdateDroneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDroneRequest.ProtoReflect.Descriptor instead.
func (*UpdateDroneRequest) Descriptor() ([]byte, []int) {
	return file_proto_drone_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDroneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDroneRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDroneRequest) GetCharge() int32 {
	if x != nil {
		return x.Charge
	}
	return 0
}

type DroneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneResponse) Reset() {
	*x = DroneResponse{}
	mi := &file_proto_drone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneResponse) ProtoMessage() {}

func (x *DroneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneResponse.ProtoReflect.Descriptor instead.
func (*DroneResponse) Descriptor() ([]byte, []int) {
	return file_proto_drone_proto_rawDescGZIP(), []int{2}
}

func (x *DroneResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DroneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DroneListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drones        []*DroneItem           `protobuf:"bytes,1,rep,name=drones,proto3" json:"drones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneListResponse) Reset() {
	*x = DroneListResponse{}
	mi := &file_proto_drone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneListResponse) ProtoMessage() {}

func (x *DroneListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneListResponse.ProtoReflect.Descriptor instead.
func (*DroneListResponse) Descriptor() ([]byte, []int) {
	return file_proto_drone_proto_rawDescGZIP(), []int{3}
}

func (x *DroneListResponse) GetDrones() []*DroneItem {
	if x != nil {
		return x.Drones
	}
	return nil
}

type DroneItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneItem) Reset() {
	*x = DroneItem{}
	mi := &file_proto_drone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneItem) ProtoMessage() {}

func (x *DroneItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneItem.ProtoReflect.Descriptor instead.
func (*DroneItem) Descriptor() ([]byte, []int) {
	return file_proto_drone_proto_rawDescGZIP(), []int{4}
}

func (x *DroneItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DroneItem) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DroneItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_drone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_drone_proto_rawDescGZIP(), []int{5}
}

var File_proto_drone_proto protoreflect.FileDescriptor

const file_proto_drone_proto_rawDesc = "" +
	"\n" +
	"\x11proto/drone.proto\x12\x05drone\"Z\n" +
	"\x12CreateDroneRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x16\n" +
	"\x06charge\x18\x03 \x01(\x05R\x06charge\"T\n" +
	"\x12UpdateDroneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06charge\x18\x03 \x01(\x05R\x06charge\"9\n" +
	"\rDroneResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x11DroneListResponse\x12(\n" +
	"\x06drones\x18\x01 \x03(\v2\x10.drone.DroneItemR\x06drones\"I\n" +
	"\tDroneItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\a\n" +
	"\x05Empty2\xc3\x01\n" +
	"\fDroneService\x12>\n" +
	"\vCreateDrone\x12\x19.drone.CreateDroneRequest\x1a\x14.drone.DroneResponse\x123\n" +
	"\tGetDrones\x12\f.drone.Empty\x1a\x18.drone.DroneListResponse\x12>\n" +
	"\vUpdateDrone\x12\x19.drone.UpdateDroneRequest\x1a\x14.drone.DroneResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_drone_proto_rawDescOnce sync.Once
	file_proto_drone_proto_rawDescData []byte
)

func file_proto_drone_proto_rawDescGZIP() []byte {
	file_proto_drone_proto_rawDescOnce.Do(func() {
		file_proto_drone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_drone_proto_rawDesc), len(file_proto_drone_proto_rawDesc)))
	})
	return file_proto_drone_proto_rawDescData
}

var file_proto_drone_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_drone_proto_goTypes = []any{
	(*CreateDroneRequest)(nil), // 0: drone.CreateDroneRequest
	(*UpdateDroneRequest)(nil), // 1: drone.UpdateDroneRequest
	(*DroneResponse)(nil),      // 2: drone.DroneResponse
	(*DroneListResponse)(nil),  // 3: drone.DroneListResponse
	(*DroneItem)(nil),          // 4: drone.DroneItem
	(*Empty)(nil),              // 5: drone.Empty
}
var file_proto_drone_proto_depIdxs = []int32{
	4, // 0: drone.DroneListResponse.drones:type_name -> drone.DroneItem
	0, // 1: drone.DroneService.CreateDrone:input_type -> drone.CreateDroneRequest
	5, // 2: drone.DroneService.GetDrones:input_type -> drone.Empty
	1, // 3: drone.DroneService.UpdateDrone:input_type -> drone.UpdateDroneRequest
	2, // 4: drone.DroneService.CreateDrone:output_type -> drone.DroneResponse
	3, // 5: drone.DroneService.GetDrones:output_type -> drone.DroneListResponse
	2, // 6: drone.DroneService.UpdateDrone:output_type -> drone.DroneResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_drone_proto_init() }
func file_proto_drone_proto_init() {
	if File_proto_drone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_drone_proto_rawDesc), len(file_proto_drone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_drone_proto_goTypes,
		DependencyIndexes: file_proto_drone_proto_depIdxs,
		MessageInfos:      file_proto_drone_proto_msgTypes,
	}.Build()
	File_proto_drone_proto = out.File
	file_proto_drone_proto_goTypes = nil
	file_proto_drone_proto_depIdxs = nil
}
