// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/drone.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DroneService_CreateDrone_FullMethodName = "/drone.DroneService/CreateDrone"
	DroneService_GetDrones_FullMethodName   = "/drone.DroneService/GetDrones"
	DroneService_UpdateDrone_FullMethodName = "/drone.DroneService/UpdateDrone"
)

// DroneServiceClient is the client API for DroneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneServiceClient interface {
	CreateDrone(ctx context.Context, in *CreateDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error)
	GetDrones(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DroneListResponse, error)
	UpdateDrone(ctx context.Context, in *UpdateDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error)
}

type droneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneServiceClient(cc grpc.ClientConnInterface) DroneServiceClient {
	return &droneServiceClient{cc}
}

func (c *droneServiceClient) CreateDrone(ctx context.Context, in *CreateDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, DroneService_CreateDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) GetDrones(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DroneListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneListResponse)
	err := c.cc.Invoke(ctx, DroneService_GetDrones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) UpdateDrone(ctx context.Context, in *UpdateDroneRequest, opts ...grpc.CallOption) (*DroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DroneResponse)
	err := c.cc.Invoke(ctx, DroneService_UpdateDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroneServiceServer is the server API for DroneService service.
// All implementations must embed UnimplementedDroneServiceServer
// for forward compatibility.
type DroneServiceServer interface {
	CreateDrone(context.Context, *CreateDroneRequest) (*DroneResponse, error)
	GetDrones(context.Context, *Empty) (*DroneListResponse, error)
	UpdateDrone(context.Context, *UpdateDroneRequest) (*DroneResponse, error)
	mustEmbedUnimplementedDroneServiceServer()
}

// UnimplementedDroneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDroneServiceServer struct{}

func (UnimplementedDroneServiceServer) CreateDrone(context.Context, *CreateDroneRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDrone not implemented")
}
func (UnimplementedDroneServiceServer) GetDrones(context.Context, *Empty) (*DroneListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrones not implemented")
}
func (UnimplementedDroneServiceServer) UpdateDrone(context.Context, *UpdateDroneRequest) (*DroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDrone not implemented")
}
func (UnimplementedDroneServiceServer) mustEmbedUnimplementedDroneServiceServer() {}
func (UnimplementedDroneServiceServer) testEmbeddedByValue()                      {}

// UnsafeDroneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneServiceServer will
// result in compilation errors.
type UnsafeDroneServiceServer interface {
	mustEmbedUnimplementedDroneServiceServer()
}

func RegisterDroneServiceServer(s grpc.ServiceRegistrar, srv DroneServiceServer) {
	// If the following call panics, it indicates UnimplementedDroneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DroneService_ServiceDesc, srv)
}

func _DroneService_CreateDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).CreateDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_CreateDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).CreateDrone(ctx, req.(*CreateDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_GetDrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).GetDrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_GetDrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).GetDrones(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_UpdateDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).UpdateDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_UpdateDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).UpdateDrone(ctx, req.(*UpdateDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DroneService_ServiceDesc is the grpc.ServiceDesc for DroneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.DroneService",
	HandlerType: (*DroneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDrone",
			Handler:    _DroneService_CreateDrone_Handler,
		},
		{
			MethodName: "GetDrones",
			Handler:    _DroneService_GetDrones_Handler,
		},
		{
			MethodName: "UpdateDrone",
			Handler:    _DroneService_UpdateDrone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/drone.proto",
}
